# Generated by Django 5.0.4 on 2024-04-26 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('content', models.TextField()),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
                ('id_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renting.post')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='renting/%Y/%m')),
                ('address', models.CharField(max_length=150)),
                ('num_people', models.IntegerField(null=True)),
                ('cost', models.FloatField()),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='renting.post')),
                ('room_submit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renting.roomsubmit')),
            ],
        ),
    ]
