# Generated by Django 5.0.4 on 2024-04-28 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0002_roomsubmit_post_body_post_created_at_post_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='id_post',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='id_user',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_cus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_follows', to=settings.AUTH_USER_MODEL)),
                ('user_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_follows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
