# Generated by Django 5.0.4 on 2024-05-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0006_user_is_owner_user_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_num',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
